version: '3.8'
services:
  mysql-writer:
    build:
      context: .
      dockerfile: Dockerfile-writer
    container_name: mysql-writer
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: billing
    ports:
      - "3305:3306"
    networks:
      - my_network

  mysql-read:
    build:
      context: .
      dockerfile: Dockerfile-reader
    container_name: mysql-reader
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: billing
    ports:
      - "3307:3306"
    networks:
      - my_network
    depends_on:
      - mysql-writer

networks:
  my_network:
    driver: bridge