name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

    strategy:
      matrix:
        module: [module-user, module-streaming]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # MySQL 설정 및 테스트
      - name: Build and run Docker Compose
        run: docker-compose -f docker-compose-mysql.yml up -d

      - name: Test MySQL connection
        run: docker exec billing-project_mysql_1 mysql -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "SHOW DATABASES;"

      # Java 및 Gradle 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ matrix.module }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ matrix.module }}-

      # 모듈별 설정 파일 생성
      - name: Create module-specific application.yml
        run: |
          mkdir -p ${{ matrix.module }}/src/main/resources
          mkdir -p ${{ matrix.module }}/src/test/resources
          app_yml_var="MODULE_${{ matrix.module | toUpper }}_APPLICATION_YML"
          test_yml_var="MODULE_${{ matrix.module | toUpper }}_TEST_YML"
          echo "${{ secrets[app_yml_var] }}" | base64 --decode > ${{ matrix.module }}/src/main/resources/application.yml
          echo "${{ secrets[test_yml_var] }}" | base64 --decode > ${{ matrix.module }}/src/test/resources/application.yml
          echo "${{ matrix.module }} module application.yml:"
          cat ${{ matrix.module }}/src/main/resources/application.yml
          echo "${{ matrix.module }} module test application.yml:"
          cat ${{ matrix.module }}/src/test/resources/application.yml

      # 빌드 및 테스트 실행
      - name: Build and Test ${{ matrix.module }}
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3305/billing
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: |
          ./gradlew :${{ matrix.module }}:build --warning-mode all
          ./gradlew :${{ matrix.module }}:test --warning-mode all

      # 정리 작업
      - name: Stop Docker Compose
        if: always()
        run: docker-compose -f docker-compose-mysql.yml down