name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run Docker Compose
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: |
          docker-compose -f docker-compose-mysql.yml up -d   

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create module-user application.yml
        run: |
          mkdir -p module-user/src/main/resources
          mkdir -p module-user/src/test/resources
          echo "${{ secrets.MODULE_USER_APPLICATION_YML }}" | base64 --decode > module-user/src/main/resources/application.yml
          echo "${{ secrets.MODULE_USER_TEST_YML }}" | base64 --decode > module-user/src/test/resources/application.yml
          echo "User module application.yml:"
          cat module-user/src/main/resources/application.yml
          echo "User module test application.yml:"
          cat module-user/src/test/resources/application.yml

      - name: Build and test module-user
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3305/billing
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: |
          ./gradlew :module-user:build --warning-mode all
          ./gradlew :module-user:test --warning-mode all

      - name: Create module-streaming application.yml
        run: |
          mkdir -p module-streaming/src/main/resources
          mkdir -p module-streaming/src/test/resources
          echo "${{ secrets.MODULE_STREAMING_APPLICATION_YML }}" | base64 --decode > module-streaming/src/main/resources/application.yml
          echo "${{ secrets.MODULE_STREAMING_TEST_YML }}" | base64 --decode > module-streaming/src/test/resources/application.yml
          echo "Streaming module application.yml:"
          cat module-streaming/src/main/resources/application.yml
          echo "Streaming module test application.yml:"
          cat module-streaming/src/test/resources/application.yml

      - name: Build and test module-streaming
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3305/billing
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: |
          ./gradlew :module-streaming:build --warning-mode all
          ./gradlew :module-streaming:test --warning-mode all
