name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

    strategy:
      matrix:
        module: [module-user, module-streaming]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # MySQL 설정 및 테스트
      - name: Build and run Docker Compose
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: docker-compose -f docker-compose-mysql.yml up -d

      - name: Test MySQL connection
        run: docker exec billing-project_mysql_1 mysql -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "SHOW DATABASES;"

      # Java 및 Gradle 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 모듈별 설정 파일 생성
      - name: Create module-specific application.yml
        run: |
          mkdir -p ${{ matrix.module }}/src/main/resources
          mkdir -p ${{ matrix.module }}/src/test/resources
          if [ "${{ matrix.module }}" = "module-user" ]; then
            echo "${{ secrets.MODULE_USER_APPLICATION_YML }}" | base64 --decode > ${{ matrix.module }}/src/main/resources/application.yml
            echo "${{ secrets.MODULE_USER_TEST_YML }}" | base64 --decode > ${{ matrix.module }}/src/test/resources/application.yml
            echo "User module application.yml:"
            cat ${{ matrix.module }}/src/main/resources/application.yml
            echo "User module test application.yml:"
            cat ${{ matrix.module }}/src/test/resources/application.yml
          elif [ "${{ matrix.module }}" = "module-streaming" ]; then
            echo "${{ secrets.MODULE_STREAMING_APPLICATION_YML }}" | base64 --decode > ${{ matrix.module }}/src/main/resources/application.yml
            echo "${{ secrets.MODULE_STREAMING_TEST_YML }}" | base64 --decode > ${{ matrix.module }}/src/test/resources/application.yml
            echo "Streaming module application.yml:"
            cat ${{ matrix.module }}/src/main/resources/application.yml
            echo "Streaming module test application.yml:"
            cat ${{ matrix.module }}/src/test/resources/application.yml
          else
            echo "Unknown module: ${{ matrix.module }}"
            exit 1

      # 빌드 및 테스트 실행
      - name: Build ${{ matrix.module }}
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3305/billing
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: ./gradlew :${{ matrix.module }}:build --warning-mode all

      - name: Run tests ${{ matrix.module }}
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3305/billing
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: ./gradlew :${{ matrix.module }}:test --warning-mode all