name: JPA Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3305:3306
        options: >-
          --health-cmd='mysqladmin ping --silent'
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: billing

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Wait for MySQL to be healthy
        run: |
          echo "Waiting for MySQL to be ready..."
          until docker exec mysql-container mysqladmin ping -h "localhost" --port=3305 --silent; do
            echo "MySQL is unavailable - sleeping"
            sleep 5
          done
          echo "MySQL is up - executing command"

#      - name: MySQL create database
#        env:
#          MYSQL_PWD: admin
#        run: docker exec mysql-container mysql -h localhost --port=3305 -uroot -padmin -e "CREATE DATABASE billing;"

      - name: Test MySQL connection
        env:
          MYSQL_PWD: admin
        run: docker exec mysql-container mysql -h localhost --port=3305 -uroot -padmin -e "SHOW DATABASES;"

      - name: Run JPA tests
        run: ./gradlew build test
        env:
          SPRING_PROFILES_ACTIVE: ci
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: billing

      - name: Print application logs
        run: cat build/test-results/test/*.xml

      - name: Stop Docker Compose
        run: docker-compose down
