name: JPA Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Wait for MySQL to be healthy
        run: |
          echo "Waiting for MySQL to be ready..."
          until docker exec mysql-container mysqladmin ping -h "localhost" --silent; do
            echo "MySQL is unavailable - sleeping"
            sleep 5
          done
          echo "MySQL is up - executing command"

      - name: Test MySQL connection
        env:
          MYSQL_PWD: admin
        run: docker exec mysql-container mysql -uroot -padmin -e "SHOW DATABASES;"

      - name: Create billing database
        env:
          MYSQL_PWD: admin
        run: docker exec mysql-container mysql -uroot -padmin -e "CREATE DATABASE billing;"

      - name: Run JPA tests
        run: ./gradlew build test
        env:
          SPRING_PROFILES_ACTIVE: ci
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: billing  # 여기에 생성한 데이터베이스 이름을 추가

      - name: Print application logs
        run: cat build/test-results/test/*.xml

      - name: Stop Docker Compose
        run: docker-compose down
